### ISSUE TITLE
NFS issue

### ISSUE THREAD

**Issue by juanfernandes** [PerchCMS/perch-vagrant#1]
This is the first time I have tried vagrant, so far I'm very impressed.

I'm using Ubuntu.

On running the box for the first time I got the following error message:
vm:
- It appears your machine doesn't support NFS, or there is not an
  adapter to enable NFS on this machine for Vagrant. Please verify
  that `nfsd` is installed on your machine, and try again. If you're
  on Windows, NFS isn't supported. If the problem persists, please
  contact Vagrant support.

**Comment by rachelandrew** [comment]
I developed this on a Mac, I think nfs is just ignored if not available. I'll make that a setting at some point.

**Comment by juanfernandes** [comment]
Thanks Rachel, I thought that might be the case. Just thought I'd highlight it.

**Comment by juanfernandes** [comment]
This issue was resolved by installing NFS :smile_cat: 

sudo apt-get install nfs-server
