### ISSUE TITLE
Connecting to the database

### ISSUE THREAD

**Issue by juanfernandes** [PerchCMS/perch-vagrant#2]
Sorry, not really an issue, more lack of knowledege, but I have searched to no avail. 

How are you connecting to the database? I'm using MySQL Workbench to try and connect to the database but I don't know what settings I should be using:

Connection method: Standard (TCP/IP) or Standard (TCP/IP) over SSH

I don't expect you to know how MySql Workbench works, but could you share what settings you used to connect to it? 

Thanks

**Comment by rachelandrew** [comment]
I don't know and I'm afraid I can't offer support for this for every environment. It's provided "as is" as a starting point.

**Comment by juanfernandes** [comment]
Figured it out.

![mysqlworkbench](https://cloud.githubusercontent.com/assets/355046/6851664/5d61cf16-d3d8-11e4-8449-64d12df8ab03.png)
