### ISSUE TITLE
PHP not enabled by default

### ISSUE THREAD

**Issue by abberdab** [PerchCMS/perch-vagrant#3]
More comments than issues. FYI's with no expectation of support. In my copy of this vagrant VM, PHP was not enabled by default after running `vagrant up`. My php displayed as code in the browser. Thought I'd leave a note here about how I addressed that.

After running `vagrant up`, I used `vagrant ssh` to log into the vagrant VM, enabled php `sudo a2enmod php5` and then restarted apache `service apache2 restart`.

Possibly related, at a point during my PHP troubleshooting, I noticed an error in my terminal after running `vagrant up`: 

> The guest additions on this VM do not match the installed version of VirtualBox! In most cases this is fine, but in rare cases it can prevent things such as shared folders from working properly. If you see shared folder errors, please make sure the guest additions within the virtual machine match the version of VirtualBox you have installed on your host and reload your VM.

I’m running VirtualBox 5.0.8. My guest additions (if I recall correctly, I don't have a record of this) were something like 4.X.X. 

After Googling the above error, I found a vagrant plugin for installing/upgrading VirtualBox Guest Additions. The following command brought my guest additions in line with my installed version of VirtualBox and cleared up the error: `vagrant plugin install vagrant-vbguest`

**Comment by montlewis** [comment]
Thanks, Abbigail! This ended a day of headaches for me as I couldn't figure out why PHP wasn't running!

**Comment by abberdab** [comment]
You're welcome, Monty! I'm glad to hear my post helped someone. :)

**Comment by rachelandrew** [comment]
This shouldn't be an issue with the updated version of this package. No need to upgrade anything running but if you provision a new one it should be fixed.
